version: 0.1
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region eu-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo -n `date "+%Y%m%d%H%M%S"` > BUILD_TAG.txt       
      - docker build --build-arg COMPOSER_USER="$COMPOSER_USER" --build-arg COMPOSER_PASS="$COMPOSER_PASS" -t knowthething:`cat BUILD_TAG.txt` .
      - docker tag knowthething:`cat BUILD_TAG.txt` eu-west-2.dkr.ecr.613903586696.amazonaws.com/knowthething:`cat BUILD_TAG.txt`
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 613903586696.dkr.ecr.eu-west-2.amazonaws.com/knowthething:`cat BUILD_TAG.txt`
      # - ./deploy-aws.sh knowthething-dev wp-dev "$ECR_REPOSITORY:branch-$CIRCLE_BRANCH"
