version: 0.1
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region eu-west-2)
  build:
    commands:
      - aws codepipeline get-pipeline-execution --pipeline-name `echo $CODEBUILD_INITIATOR | cut -f 2 -d '/'` --pipeline-execution-id `aws codepipeline get-pipeline-state --name $(echo $CODEBUILD_INITIATOR | cut -f 2 -d '/') --query "stageStates[?actionStates[0].actionName=='CodeBuild'].latestExecution.pipelineExecutionId" --output text` --query "pipelineExecution.artifactRevisions[?name=='DockerRepo'].revisionId" --output text
      - echo -n `git rev-parse --short HEAD` > BUILD_TAG.txt && echo -n -`date "+%Y%m%d%H%M"` >> BUILD_TAG.txt
      - echo Created build tag `cat BUILD_TAG.txt`
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg COMPOSER_USER="$COMPOSER_USER" --build-arg COMPOSER_PASS="$COMPOSER_PASS" -t knowthething:`cat BUILD_TAG.txt` .
      - docker tag knowthething:`cat BUILD_TAG.txt` 613903586696.dkr.ecr.eu-west-2.amazonaws.com/wp/knowthething:`cat BUILD_TAG.txt`
  post_build:
    commands:
      - echo Using build tag `cat BUILD_TAG.txt`
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 613903586696.dkr.ecr.eu-west-2.amazonaws.com/wp/knowthething:`cat BUILD_TAG.txt`
artifacts:
  files:
    - BUILD_TAG.txt
